### ISSUE TITLE
Wiki - GetImage API missing properties

### ISSUE THREAD

**Issue by JohnGoyette** [dsimaging/dsio-filters-api#1]
The _createdOn_ and _expires_ properties are missing from the documented API call for [Get Image](https://github.com/dsimaging/dsio-filters-api/wiki/Images#get-image-resource-) in the Wiki.

**Comment by jtetro2** [comment]
@JohnGoyette I have updated the WiKi to include the missing properties.

**Comment by JohnGoyette** [comment]
Changes look good to me. I will close the issue.
