### ISSUE TITLE
Update docs with new Get Image Media API

### ISSUE THREAD

**Issue by JohnGoyette** [dsimaging/dsio-filters-api#2]
Similar to the Modality API issue for [media access](https://github.com/dsimaging/dsio-modality-api/issues/2), we need to make sure that the _url_ property of _ImageResource_ is a documented API. A new API method GET /images/{id}/media was created for this purpose.

The OpenAPI spec, the ReDoc page and the Wiki must be updated with this new API call.

**Comment by JohnGoyette** [comment]
The OpenAPI spec and Redoc files have been updated with this new API. The SDK was also updated.

@jtetro2, we have only the Wiki to update and we can close this issue.

**Comment by jtetro2** [comment]
@JohnGoyette, the WiKi has been updated, per your comments.

**Comment by JohnGoyette** [comment]
I do not see the added API in the Wiki.

**Comment by jtetro2** [comment]
@JohnGoyette,

The Get Image Media API, and your other suggestions regarding additional sidelinks (here and in the Modality API WiKi), and Response information for the Filters APIs, are incorporated.

**Comment by JohnGoyette** [comment]
Looks good. Thanks, @jtetro2
